python main.py --num-classes 5 --num-workers 12 --num-epochs 60 --batch-size 128 --valid-data-dir 'data/DDR/test' --log-dir 'tf-logs' --lr 1e-3 --input-size 480 --kernel-size 9 --dim 128 --patch-size 8 --backbone patch
python main.py --num-classes 5 --num-workers 12 --num-epochs 60 --batch-size 32 --valid-data-dir 'data/DDR/test' --log-dir 'tf-logs' --lr 2e-5 --input-size 480 --kernel-size 1 --backbone convnext_base --pretrained
python main.py --num-classes 5 --num-workers 12 --num-epochs 60 --batch-size 32 --valid-data-dir 'data/DDR/test' --log-dir 'tf-logs' --lr 2e-5 --input-size 480 --kernel-size 1 --backbone efficientnet --pretrained
python main.py --num-classes 5 --num-workers 12 --num-epochs 60 --batch-size 32 --valid-data-dir 'data/DDR/test' --log-dir 'tf-logs' --lr 2e-5 --input-size 480 --kernel-size 1 --backbone densenet161 --pretrained
python main.py --num-classes 5 --num-workers 12 --num-epochs 60 --batch-size 32 --valid-data-dir 'data/DDR/test' --log-dir 'tf-logs' --lr 2e-5 --input-size 480 --kernel-size 1 --backbone densenet121 --pretrained
python main.py --num-classes 5 --num-workers 12 --num-epochs 60 --batch-size 32 --valid-data-dir 'data/DDR/test' --log-dir 'tf-logs' --lr 2e-5 --input-size 384 --kernel-size 1 --backbone convnext_base --pretrained
python main.py --num-classes 5 --num-workers 12 --num-epochs 60 --batch-size 32 --valid-data-dir 'data/DDR/test' --log-dir 'tf-logs' --lr 2e-5 --input-size 384 --kernel-size 1 --backbone efficientnet --pretrained
python main.py --num-classes 5 --num-workers 12 --num-epochs 60 --batch-size 32 --valid-data-dir 'data/DDR/test' --log-dir 'tf-logs' --lr 2e-5 --input-size 384 --kernel-size 1 --backbone densenet121 --pretrained
python main.py --num-classes 5 --num-workers 12 --num-epochs 60 --batch-size 32 --valid-data-dir 'data/DDR/test' --log-dir 'tf-logs' --lr 2e-5 --input-size 384 --kernel-size 1 --backbone densenet161 --pretrained
python main.py --num-classes 5 --num-workers 12 --num-epochs 60 --batch-size 32 --valid-data-dir 'data/DDR/test' --log-dir 'tf-logs' --lr 2e-5 --input-size 224 --kernel-size 1 --backbone convnext_base --pretrained
python main.py --num-classes 5 --num-workers 12 --num-epochs 60 --batch-size 32 --valid-data-dir 'data/DDR/test' --log-dir 'tf-logs' --lr 2e-5 --input-size 224 --kernel-size 1 --backbone efficientnet --pretrained
python main.py --num-classes 5 --num-workers 12 --num-epochs 60 --batch-size 32 --valid-data-dir 'data/DDR/test' --log-dir 'tf-logs' --lr 2e-5 --input-size 224 --kernel-size 1 --backbone densenet161 --pretrained
python main.py --num-classes 5 --num-workers 12 --num-epochs 60 --batch-size 32 --valid-data-dir 'data/DDR/test' --log-dir 'tf-logs' --lr 2e-5 --input-size 224 --kernel-size 1 --backbone densenet121 --pretrained